version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: map
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017

volumes:
  mongo-data:
